# Generated by Django 3.2.2 on 2021-05-07 04:51

from django.db import migrations, models
import item_builder.managers


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', item_builder.managers.DiscordUserAuthManager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
