# Generated by Django 3.2.2 on 2021-05-07 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0002_auto_20210507_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('img_src', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('stats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('hero', models.CharField(max_length=25)),
                ('desc', models.TextField()),
                ('items', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_builder.discorduser')),
            ],
        ),
    ]
