# Generated by Django 3.2.2 on 2021-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0003_builds_heroes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='id',
        ),
        migrations.AlterField(
            model_name='heroes',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
