# Generated by Django 3.2.2 on 2021-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0004_auto_20210507_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('cost', models.IntegerField()),
                ('active', models.TextField()),
                ('passive', models.TextField()),
                ('stats', models.TextField()),
                ('unique_passive', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='builds',
            name='liked_users',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='builds',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
