# Generated by Django 3.2.2 on 2021-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0006_auto_20210513_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
