# Generated by Django 3.2.2 on 2021-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0007_builds_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builds',
            name='items',
        ),
        migrations.AddField(
            model_name='builds',
            name='early_items',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='builds',
            name='late_items',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='builds',
            name='mid_items',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='builds',
            name='starter_items',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='builds',
            name='desc',
            field=models.CharField(max_length=250),
        ),
    ]
