# Generated by Django 3.2.2 on 2021-05-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0008_auto_20210515_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='liked_builds',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='heroes',
            name='abilities',
            field=models.TextField(default='Q:|E:|R:|RMB:|P:'),
        ),
    ]
