# Generated by Django 3.2.2 on 2021-05-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0011_builds_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_builder.heroes'),
        ),
    ]
