# Generated by Django 3.2.2 on 2021-05-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0012_alter_builds_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_listed', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_builder.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='BannedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_banned', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_builder.discorduser')),
            ],
        ),
    ]
