# Generated by Django 3.2.2 on 2021-05-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0013_bannedusers_whitelistedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistedusers',
            name='user',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BannedUsers',
        ),
        migrations.DeleteModel(
            name='WhitelistedUsers',
        ),
    ]
