# Generated by Django 3.2.2 on 2021-05-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0014_auto_20210530_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='late_items',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='builds',
            name='mid_items',
            field=models.CharField(default='', max_length=100),
        ),
    ]
