# Generated by Django 3.2.2 on 2021-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0015_auto_20210530_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='author_name',
            field=models.CharField(default='ArcticStorm9#6506', max_length=50),
            preserve_default=False,
        ),
    ]
