# Generated by Django 3.2.2 on 2021-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0016_builds_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builds',
            name='liked_users',
        ),
    ]
