# Generated by Django 3.2.2 on 2021-06-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_builder', '0018_remove_builds_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='early_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='builds',
            name='late_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='builds',
            name='mid_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='builds',
            name='starter_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='liked_builds',
            field=models.JSONField(default=[]),
        ),
    ]
